require('dotenv').config();
const path = require('path');
const fs = require('fs');

const fetchNewImages = require('./gumroad_fetcher');
const createPhotoVideo = require('./generator');
const uploadToPinterest = require('./uploader/pinterest');
const uploadToTikTok = require('./uploader/tiktok');

(async () => {
  try {
    console.log("Fetching new images...");
    const images = await fetchNewImages();

    if (!images || images.length === 0) {
      console.log("No new images to process.");
      return;
    }

    console.log("Generating video...");
    const videoPath = await createPhotoVideo(images);

    console.log("Uploading to Pinterest...");
    await uploadToPinterest({
      imagePath: images[0],
      title: "New Aesthetic Wallpaper",
      description: "Generated by the Marketing Bot"
    });

    console.log("Uploading to TikTok...");
    await uploadToTikTok({
      videoPath,
      caption: "New AI aesthetic video 💫"
    });

    console.log("Done!");
  } catch (err) {
    console.error("Error running bot:", err);
    process.exit(1);
  }
})();
